export { default as ChangeEmail } from './ChangeEmail'
export { default as ChangePassword } from './ChangePassword'
export { default as DishDetail } from './DishDetail'
export { default as DishEdit } from './DishEdit'
export { default as DishList } from './DishList'
export { default as ResetPassword } from './ResetPassword'
export { default as SignIn } from './SignIn'
export { default as SignUp } from './SignUp'
